sudo: false
language: node_js
node_js:
    - 6
    - 8
    - 9
    - 10
    - 11
cache:
    directories:
        - node_modules
script:
    - npm run prettier-check
    - npm run build
    - npm run test
notifications:
    email: false
